[2024-06-30 18:47:29,249] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_datalake_dag.create_datalake_table manual__2024-06-30T18:47:28.488041+00:00 [queued]>
[2024-06-30 18:47:29,337] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_datalake_dag.create_datalake_table manual__2024-06-30T18:47:28.488041+00:00 [queued]>
[2024-06-30 18:47:29,339] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 18:47:29,339] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-30 18:47:29,339] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 18:47:29,358] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_datalake_table> on 2024-06-30 18:47:28.488041+00:00
[2024-06-30 18:47:29,376] {standard_task_runner.py:52} INFO - Started process 874 to run task
[2024-06-30 18:47:29,381] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_datalake_dag', 'create_datalake_table', 'manual__2024-06-30T18:47:28.488041+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpuphmy83l', '--error-file', '/tmp/tmp9_rxh__g']
[2024-06-30 18:47:29,382] {standard_task_runner.py:80} INFO - Job 7: Subtask create_datalake_table
[2024-06-30 18:47:29,462] {task_command.py:371} INFO - Running <TaskInstance: example_datalake_dag.create_datalake_table manual__2024-06-30T18:47:28.488041+00:00 [running]> on host 12d6cc628018
[2024-06-30 18:47:29,525] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_datalake_dag
AIRFLOW_CTX_TASK_ID=create_datalake_table
AIRFLOW_CTX_EXECUTION_DATE=2024-06-30T18:47:28.488041+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-30T18:47:28.488041+00:00
[2024-06-30 18:47:29,536] {base.py:68} INFO - Using connection ID 'datalake_postgres' for task execution.
[2024-06-30 18:47:29,552] {dbapi.py:231} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS datalake_table (
            id SERIAL PRIMARY KEY,
            data VARCHAR(50)
        );
        , parameters: None
[2024-06-30 18:47:29,553] {postgres.py:94} INFO - NOTICE:  relation "datalake_table" already exists, skipping

[2024-06-30 18:47:29,564] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=example_datalake_dag, task_id=create_datalake_table, execution_date=20240630T184728, start_date=20240630T184729, end_date=20240630T184729
[2024-06-30 18:47:29,596] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-06-30 18:47:29,620] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
